spring.application.name=task

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db.lghslltbqqsqacxvjtaz.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Silenze#7904

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Server
server.address=0.0.0.0
server.compression.enabled=false

# Async Timeout
spring.mvc.async.request-timeout=5000